apiVersion: apps/v1
kind: Deployment
metadata:
  name: testserver
  labels:
    app: testserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testserver
  template:
    metadata:
      labels:
        app: testserver
    spec:
      containers:
        - name: testserver
          image: registry-dal2.penguintech.io/waddleperf/testserver:latest
          ports:
            - containerPort: 8080
