[pytest]
asyncio_mode = auto
testpaths = tests
addopts = --cov=client --cov-report=xml --cov-report=term-missing --cov-fail-under=90

[coverage:run]
omit =
    tests/*
    */site-packages/*

[coverage:report]
omit =
    tests/*
    */site-packages/*
exclude_lines =
    pragma: no cover
    def __repr__
    raise AssertionError
    raise NotImplementedError
    if __name__ == .__main__.:
