apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: waddleperf-alpha
namePrefix: alpha-
commonLabels:
  environment: alpha
resources:
  - ../../base
replicas:
  - name: testserver
    count: 1
  - name: unified-api
    count: 1
  - name: webui
    count: 1
images:
  - name: registry-dal2.penguintech.io/waddleperf/testserver
    newTag: latest
  - name: registry-dal2.penguintech.io/waddleperf/unified-api
    newTag: latest
  - name: registry-dal2.penguintech.io/waddleperf/webui
    newTag: latest
configMapGenerator:
  - name: waddleperf-config
    behavior: merge
    literals:
      - LOG_LEVEL=DEBUG
      - RELEASE_MODE=false
