name: Testserver Build Up
on:
  push:
    branches: [ "v4.1.x" ] # Use explicit quoting for safety
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Minimal workflow triggered and ran successfully."
