name: Debug Build Meta V2

on:
  push:
    branches: ["v4.1.x"]

permissions:
  contents: write
  packages: write

...
  build:
    name: Build and push
    runs-on: ubuntu-latest
    needs: [metadata, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/penguintechinc/waddleperf-testserver
          tags: |
            type=raw,value=${{ needs.metadata.outputs.tag }}
      - run: echo "Meta tags: ${{ steps.meta.outputs.tags }}"
